# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### general config options #####
datadir = "data"

##### advanced configuration options #####

##### consensus configuration options #####
[consensus]
# Enable mining
mine = true
# Consensus type
type = "pow"

##### p2p server configuration options #####
[network]

# Address to listen for incoming connections
listen = "/ip4/127.0.0.1/tcp/9998"

# Comma separated list of seed nodes to connect to
#seeds = "f3007be6a76e50abaa04dfd437ce8611332eaba917d78a619cf8258b68cb0a8f@/ip4/127.0.0.1/tcp/9998"

# Network private key file path
privatekey = "node1.key"

##### dht configuration options #####
[dht]
# Bucket size of routine table
bucketsize = 2

